package com.unscramble.app.model

import com.unscramble.app.R

object FlagData {

    val easyFlags = mapOf(
        "ABD" to R.drawable.flag_abd,
        "Afganistan" to R.drawable.flag_afganistan,
        "Almanya" to R.drawable.flag_almanya,
        "Arjantin" to R.drawable.flag_arjantin,
        "Avustralya" to R.drawable.flag_avustralya,
        "Azerbaycan" to R.drawable.flag_azerbaycan,
        "Belçika" to R.drawable.flag_belcika,
        "Birleşik Krallık" to R.drawable.flag_birlesik_krallik,
        "Brezilya" to R.drawable.flag_brezilya,
        "Çekya" to R.drawable.flag_cekya,
        "Çin" to R.drawable.flag_cin,
        "Danimarka" to R.drawable.flag_danimarka,
        "Endonezya" to R.drawable.flag_endonezya,
        "Filistin" to R.drawable.flag_filistin,
        "Finlandiya" to R.drawable.flag_finlandiya,
        "Fransa" to R.drawable.flag_fransa,
        "Güney Afrika" to R.drawable.flag_guney_afrika,
        "Güney Kore" to R.drawable.flag_guney_kore,
        "Hindistan" to R.drawable.flag_hindistan,
        "Hollanda" to R.drawable.flag_hollanda,
        "Irak" to R.drawable.flag_irak,
        "İran" to R.drawable.flag_iran,
        "İspanya" to R.drawable.flag_ispanya,
        "İsrail" to R.drawable.flag_israil,
        "İsviçre" to R.drawable.flag_isvicre,
        "İtalya" to R.drawable.flag_italya,
        "Japonya" to R.drawable.flag_japonya,
        "Kanada" to R.drawable.flag_kanada,
        "Kıbrıs" to R.drawable.flag_kibris,
        "Kuzey Kore" to R.drawable.flag_kuzey_kore,
        "Meksika" to R.drawable.flag_meksika,
        "Mısır" to R.drawable.flag_misir,
        "Nepal" to R.drawable.flag_nepal,
        "Norveç" to R.drawable.flag_norvec,
        "Pakistan" to R.drawable.flag_pakistan,
        "Polonya" to R.drawable.flag_polonya,
        "Portekiz" to R.drawable.flag_portekiz,
        "Romanya" to R.drawable.flag_romanya,
        "Rusya" to R.drawable.flag_rusya,
        "Sırbistan" to R.drawable.flag_sirbistan,
        "Suriye" to R.drawable.flag_suriye,
        "Suudi Arabistan" to R.drawable.flag_suudi_arabistan,
        "Tayland" to R.drawable.flag_tayland,
        "Türkiye" to R.drawable.flag_turkiye,
        "Ukrayna" to R.drawable.flag_ukranya,
        "Yunanistan" to R.drawable.flag_yunanistan
    )

    val mediumFlags = mapOf(
        "Arnavutluk" to R.drawable.flag_arnavutluk,
        "Avusturya" to R.drawable.flag_avusturya,
        "Birleşik Arap Emirlikleri" to R.drawable.flag_birlesik_arap_emirlikleri,
        "Bolivya" to R.drawable.flag_bolivya,
        "Bosna Hersek" to R.drawable.flag_bosna_hersek,
        "Bulgaristan" to R.drawable.flag_bulgaristan,
        "Burkina Faso" to R.drawable.flag_burkina_faso,
        "Cezayir" to R.drawable.flag_cezayir,
        "Dominik Cumhuriyeti" to R.drawable.flag_dominik_cumhuriyeti,
        "Ekvador" to R.drawable.flag_ekvador,
        "Ermenistan" to R.drawable.flag_ermenistan,
        "Estonya" to R.drawable.flag_estonya,
        "Etiyopya" to R.drawable.flag_etiyopya,
        "Fas" to R.drawable.flag_fas,
        "Fildişi Sahili" to R.drawable.flag_fildisi_sahili,
        "Filipinler" to R.drawable.flag_filipinler,
        "Gana" to R.drawable.flag_gana,
        "İrlanda" to R.drawable.flag_irlanda,
        "Hırvatistan" to R.drawable.flag_hirvatistan,
        "Gürcistan" to R.drawable.flag_gurcistan,
        "İsveç" to R.drawable.flag_isvec,
        "İzlanda" to R.drawable.flag_izlanda,
        "Jamaika" to R.drawable.flag_jamaika,
        "Kamerun" to R.drawable.flag_kamerun,
        "Karadağ" to R.drawable.flag_karadag,
        "Katar" to R.drawable.flag_katar,
        "Kazakistan" to R.drawable.flag_kazakistan,
        "Kenya" to R.drawable.flag_kenya,
        "Kırgızistan" to R.drawable.flag_kirgizistan,
        "Kolombiya" to R.drawable.flag_kolombiya,
        "Kosta Rika" to R.drawable.flag_kosta_rika,
        "Küba" to R.drawable.flag_kuba,
        "Kuveyt" to R.drawable.flag_kuveyt,
        "Kuzey Makedonya" to R.drawable.flag_kuzey_makedonya,
        "Letonya" to R.drawable.flag_letonya,
        "Libya" to R.drawable.flag_libya,
        "Lübnan" to R.drawable.flag_lubnan,
        "Lüksemburg" to R.drawable.flag_luksemburg,
        "Macaristan" to R.drawable.flag_macaristan,
        "Malezya" to R.drawable.flag_malezya,
        "Malta" to R.drawable.flag_malta,
        "Moğolistan" to R.drawable.flag_mogolistan,
        "Monako" to R.drawable.flag_monako,
        "Nijer" to R.drawable.flag_nijer,
        "Nijerya" to R.drawable.flag_nijerya,
        "Özbekistan" to R.drawable.flag_ozbekistan,
        "Panama" to R.drawable.flag_panama,
        "Paraguay" to R.drawable.flag_paraguay,
        "Peru" to R.drawable.flag_peru,
        "Şili" to R.drawable.flag_sili,
        "Singapur" to R.drawable.flag_singapur,
        "Slovakya" to R.drawable.flag_slovakya,
        "Slovenya" to R.drawable.flag_slovenya,
        "Sudan" to R.drawable.flag_sudan,
        "Tacikistan" to R.drawable.flag_tacikistan,
        "Tanzanya" to R.drawable.flag_tanzanya,
        "Tunus" to R.drawable.flag_tunus,
        "Türkmenistan" to R.drawable.flag_turkmenistan,
        "Ürdün" to R.drawable.flag_urdun,
        "Uruguay" to R.drawable.flag_uruguay,
        "Venezuela" to R.drawable.flag_venezuela,
        "Vietnam" to R.drawable.flag_vietnam,
        "Yemen" to R.drawable.flag_yemen,
        "Yeni Zelanda" to R.drawable.flag_yeni_zelanda
    )

    val hardFlags = mapOf(
        "Andorra" to R.drawable.flag_andorra,
        "Angola" to R.drawable.flag_angola,
        "Antigua ve Barbuda" to R.drawable.flag_antigua_ve_barbuda,
        "Bahamalar" to R.drawable.flag_bahamalar,
        "Bahreyn" to R.drawable.flag_bahreyn,
        "Bangladeş" to R.drawable.flag_banglades,
        "Barbados" to R.drawable.flag_barbados,
        "Belarus" to R.drawable.flag_belarus,
        "Belize" to R.drawable.flag_belize,
        "Benin" to R.drawable.flag_benin,
        "Botsvana" to R.drawable.flag_botsvana,
        "Brunei" to R.drawable.flag_brunei,
        "Burundi" to R.drawable.flag_burundi,
        "Butan" to R.drawable.flag_butan,
        "Cabo Verde" to R.drawable.flag_cabo_verde,
        "Çad" to R.drawable.flag_cad,
        "Cibuti" to R.drawable.flag_cibuti,
        "Dominika" to R.drawable.flag_dominika,
        "Ekvator Ginesi" to R.drawable.flag_ekvator_ginesi,
        "El Salvador" to R.drawable.flag_el_salvador,
        "Eritre" to R.drawable.flag_eritre,
        "Esvatini" to R.drawable.flag_esvatini,
        "Fiji" to R.drawable.flag_fiji,
        "Gabon" to R.drawable.flag_gabon,
        "Gambiya" to R.drawable.flag_gambiya,
        "Gine Bissau" to R.drawable.flag_gine_bissau,
        "Grenada" to R.drawable.flag_grenada,
        "Guetamala" to R.drawable.flag_guetamala,
        "Guyana" to R.drawable.flag_guyana,
        "Haiti" to R.drawable.flag_haiti,
        "Honduras" to R.drawable.flag_honduras,
        "Kamboçya" to R.drawable.flag_kambocya,
        "Kiribati" to R.drawable.flag_kiribati,
        "Komorlar" to R.drawable.flag_komorlar,
        "Kongo Demokratik Cumhuriyeti" to R.drawable.flag_kongo_demokratik_cumhuriyeti,
        "Kongo" to R.drawable.flag_kongo,
        "Laos" to R.drawable.flag_laos,
        "Lesoto" to R.drawable.flag_lesoto,
        "Liberya" to R.drawable.flag_liberya,
        "Lihteyştayn" to R.drawable.flag_lihtenstayn,
        "Litvanya" to R.drawable.flag_litvanya,
        "Madagaskar" to R.drawable.flag_madagaskar,
        "Malavi" to R.drawable.flag_malavi,
        "Maldivler" to R.drawable.flag_maldivler,
        "Mali" to R.drawable.flag_mali,
        "Marshall Adaları" to R.drawable.flag_marshall_adalari,
        "Mauritus" to R.drawable.flag_mauritus,
        "Mikronezya" to R.drawable.flag_mikronezya,
        "Moldova" to R.drawable.flag_moldova,
        "Moritanya" to R.drawable.flag_moritanya,
        "Mozambik" to R.drawable.flag_mozambik,
        "Myanmar" to R.drawable.flag_myanmar,
        "Namibya" to R.drawable.flag_namibya,
        "Nauru" to R.drawable.flag_nauru,
        "Nikaragua" to R.drawable.flag_nikaragua,
        "Orta Afrika Cumhuriyeti" to R.drawable.flag_orta_afrika_cumhuriyeti,
        "Palau" to R.drawable.flag_palau,
        "Papua Yeni Gine" to R.drawable.flag_papua_yeni_gine,
        "Ruanda" to R.drawable.flag_ruanda,
        "Saint Kitts ve Nevis" to R.drawable.flag_saint_kitts_ve_nevis,
        "Saint Lucia" to R.drawable.flag_saint_lucia,
        "Samoa" to R.drawable.flag_samoa,
        "San Marino" to R.drawable.flag_san_marino,
        "Sao Tome ve Principe" to R.drawable.flag_sao_tome_ve_principe,
        "Senegal" to R.drawable.flag_senegal,
        "Seyşeller" to R.drawable.flag_seyseller,
        "Sierra Leone" to R.drawable.flag_sierra_leone,
        "Solomon Adaları" to R.drawable.flag_solomon_adalari,
        "Somali" to R.drawable.flag_somali,
        "Sri Lanka" to R.drawable.flag_sri_lanka,
        "St Vincent ve Grenadinler" to R.drawable.flag_st_vincent_ve_grenadinler,
        "Surinam" to R.drawable.flag_surinam,
        "Timor Letse" to R.drawable.flag_timor_leste,
        "Togo" to R.drawable.flag_togo,
        "Tonga" to R.drawable.flag_tonga,
        "Trinidad ve Tobago" to R.drawable.flag_trinidad_ve_tobago,
        "Tuvalu" to R.drawable.flag_tuvalu,
        "Uganda" to R.drawable.flag_uganda,
        "Umman" to R.drawable.flag_umman,
        "Vanuatu" to R.drawable.flag_vanuatu,
        "Vatikan" to R.drawable.flag_vatikan,
        "Zambiya" to R.drawable.flag_zambiya,
        "Zimbabve" to R.drawable.flag_zimbabve
        )
}